events {}

http {

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://user-service:8000/;
        }

        location /api/products/ {
            proxy_pass http://product-service:3000/;
        }

        location /api/orders/ {
            proxy_pass http://order-service:8001/;
        }

    }

}